/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParser.java */
package parser;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.lang.ClassNotFoundException;

import schema.Table;
import schema.TableElement;
import schema.Column;
import schema.TableConstraint;
import schema.tableConstraint.*;
import schema.column.*;
import schema.exception.*;

import relation.Relation;
import relation.PrimaryKey;
import relation.Record;
import relation.ComparableValue;
import relation.exception.*;

import where.WhereClause;
import where.BooleanValue;
import where.BooleanValueExpression;
import where.BooleanTerm;
import where.BooleanFactor;
import where.BooleanTest;
import where.Predicate;
import where.ComparisonPredicate;
import where.CompOperand;
import where.CompOp;
import where.CompOp.OperatorType;
import where.ColumnElement;
import where.NullPredicate;
import where.exception.*;

import com.sleepycat.je.Cursor;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.Environment;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.LockMode;
import com.sleepycat.je.OperationStatus;

public class SimpleDBMSParser implements SimpleDBMSParserConstants {
  public enum Message
  {
    NONE,
    PRINT_SYNTAX_ERROR,
    PRINT_CREATE_TABLE,
    PRINT_DROP_TABLE,
    PRINT_DESC,
    PRINT_SHOW_TABLES,
    PRINT_SELECT,
    PRINT_INSERT,
    PRINT_DELETE,
  };

  public static Message q;

  public static Environment myDbEnvironment = null;
  public static EnvironmentConfig envConfig = new EnvironmentConfig();
  public static DatabaseConfig dbConfig = new DatabaseConfig();
  static {
    envConfig.setAllowCreate(true);
    myDbEnvironment = new Environment(new File("db/"), envConfig);
    dbConfig.setAllowCreate(true);
    dbConfig.setSortedDuplicates(true);
  }

  public static HashMap<String, Table> tables = new HashMap<String, Table>();

  public static void main(String args[]) throws ParseException
  {
    SimpleDBMSParser parser = new SimpleDBMSParser(System.in);

    Database myDatabase = myDbEnvironment.openDatabase(null, "table-schema", dbConfig);

    tables = (HashMap<String, Table>) load("table-schema");
    if (tables == null) tables = new HashMap<String, Table>();
    myDatabase.close();

    while (true)
    {
      try
      {
        System.out.print("DB_2014-11663> ");
        parser.command();
      }
      catch (Exception e)
      {
        printMessage(Message.PRINT_SYNTAX_ERROR);
        SimpleDBMSParser.ReInit(System.in);
      }
    }
  }

  public static void printMessage(Message q)
  {
    switch(q)
    {
      case PRINT_SYNTAX_ERROR:
        System.out.println("Syntax error");
        break;
      case PRINT_CREATE_TABLE:
        break;
      case PRINT_DROP_TABLE:
        break;
      case PRINT_DESC:
        break;
      case PRINT_SHOW_TABLES:
        break;
      case PRINT_INSERT:
        break;
      case PRINT_DELETE:
        break;
      case PRINT_SELECT:
        break;
      default:
        break;
    }
  }

  public static byte[] toBytes(Object object){
    ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
    try {
      ObjectOutputStream out = new ObjectOutputStream(byteOut);
      out.writeObject(object);
      return byteOut.toByteArray();
    } catch (IOException e) {
      e.printStackTrace();
      return null;
    }
  }

  public static Object fromBytes(byte[] bytes){
    ByteArrayInputStream byteIn = new ByteArrayInputStream(bytes);
    try {
      ObjectInputStream in = new ObjectInputStream(byteIn);
      return in.readObject();
    } catch (IOException e) {
      e.printStackTrace();
      return null;
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
      return null;
    }
  }

  public static void save(String key, Object data){
    Database myDatabase = myDbEnvironment.openDatabase(null, "db", dbConfig);
    DatabaseEntry keyEntry;
    DatabaseEntry dataEntry;
    delete(key);
    try {
      keyEntry = new DatabaseEntry(key.getBytes("UTF-8"));
      dataEntry = new DatabaseEntry(toBytes(data));
      myDatabase.put(null, keyEntry, dataEntry);
      myDatabase.close();
    } catch (DatabaseException e) {
      e.printStackTrace();
    } catch (UnsupportedEncodingException e) {
      e.printStackTrace();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
  public static Object load(String key){
    Database myDatabase = myDbEnvironment.openDatabase(null, "db", dbConfig);
    DatabaseEntry keyEntry;
    DatabaseEntry dataEntry;
    try {
      keyEntry = new DatabaseEntry(key.getBytes("UTF-8"));
      dataEntry = new DatabaseEntry();
      if (myDatabase.get(null, keyEntry, dataEntry, LockMode.DEFAULT) == OperationStatus.SUCCESS) {
        myDatabase.close();
        return fromBytes(dataEntry.getData());
      } else {
        System.err.println("Can't find " + key);
        myDatabase.close();
        return null;
      }
    } catch (DatabaseException e) {
      e.printStackTrace();
      return null;
    } catch (UnsupportedEncodingException e) {
      e.printStackTrace();
      return null;
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }
  public static void delete(String key){
    Database myDatabase = myDbEnvironment.openDatabase(null, "db", dbConfig);
    try {
      DatabaseEntry keyEntry = new DatabaseEntry(key.getBytes("UTF-8"));
      myDatabase.delete(null, keyEntry);
      myDatabase.close();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

 // Î®ºÏ? ?Çò???Ñú Î∞ëÏùò Í≤ÉÏùÑ ?çÆ?ùÑ ?úÑ?óò?ù¥ ?ûà?äî Í≤ÉÎì§?? Î∞ëÏúºÎ°? ÎπºÎÉÑ (?çî Ï¢ÅÏ? ?ùòÎØ∏Î?? ?úÑÎ°?)
  static final public void command() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE:
    case DROP:
    case DESC:
    case SHOW:
    case SELECT:
    case INSERT:
    case DELETE:
      queryList();
      break;
    case EXIT:
      jj_consume_token(EXIT);
      jj_consume_token(SEMICOLON);
      save("table-schema", tables);
      if (myDbEnvironment != null) myDbEnvironment.close();
      System.exit(0);
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void queryList() throws ParseException {
    label_1:
    while (true) {
      q = query();
      System.out.print("DB_2014-11663> ");
      printMessage(q);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CREATE:
      case DROP:
      case DESC:
      case SHOW:
      case SELECT:
      case INSERT:
      case DELETE:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

  static final public Message query() throws ParseException {
  q = Message.NONE;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE:
      createTableQuery();
      q = Message.PRINT_CREATE_TABLE;
      break;
    case DROP:
      dropTableQuery();
      q = Message.PRINT_DROP_TABLE;
      break;
    case SHOW:
      showQuery();
      q = Message.PRINT_SHOW_TABLES;
      break;
    case DESC:
      descQuery();
      q = Message.PRINT_DESC;
      break;
    case SELECT:
      selectQuery();
      q = Message.PRINT_SELECT;
      break;
    case INSERT:
      insertQuery();
      q = Message.PRINT_INSERT;
      break;
    case DELETE:
      deleteQuery();
      q = Message.PRINT_DELETE;
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return q;}
    throw new Error("Missing return statement in function");
  }

  static final public void createTableQuery() throws ParseException {
  String tableName;
  Table table;
  ArrayList<TableElement> tableElementList;
    jj_consume_token(CREATE);
    jj_consume_token(TABLE);
    tableName = tableName();
    tableElementList = tableElementList(tableName);
    jj_consume_token(SEMICOLON);
    schema.tableConstraint.ForeignKey.tables = tables;
    try {
      if (tables.containsKey(tableName)) {if (true) throw new TableExistenceError();}
      table = Table.createTable(tableName, tableElementList);
      tables.put(tableName, table);
      Relation relation = new Relation(table);
      save(tableName, relation);
      System.out.println("'" + tableName + "' table is created");
    } catch (CreateTableException e) {
      System.out.println(e.getMessage());
    } catch (Exception e) {
      System.err.println(getToken(0).image);
      e.printStackTrace();
    }
  }

  static final public ArrayList<TableElement> tableElementList(String tableName) throws ParseException {
  ArrayList<TableElement> tableElementList = new ArrayList<TableElement>();
    jj_consume_token(LEFT_PAREN);
    tableElementList.add(tableElement(tableName));
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
     tableElementList.add(tableElement(tableName));
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return tableElementList;}
    throw new Error("Missing return statement in function");
  }

  static final public TableElement tableElement(String tableName) throws ParseException {
  TableElement tableElement = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEGAL_IDENTIFIER:
      tableElement = columnDefinition(tableName);
    {if (true) return tableElement;}
      break;
    case PRIMARY:
    case FOREIGN:
      tableElement = tableConstraintDefinition();
    {if (true) return tableElement;}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Column columnDefinition(String tableName) throws ParseException {
  String columnName;
  DataType dataType;
  Boolean nullable = true;
    columnName = columnName();
    dataType = dataType();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      jj_consume_token(NULL);
      nullable = false;
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    {if (true) return new Column(tableName, columnName, dataType, nullable);}
    throw new Error("Missing return statement in function");
  }

  static final public DataType dataType() throws ParseException {
  Integer length;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
    {if (true) return new Int();}
      break;
    case CHAR:
      jj_consume_token(CHAR);
      jj_consume_token(LEFT_PAREN);
      jj_consume_token(INT_VALUE);
      Token token = getToken(0);
      length = Integer.parseInt(token.image);
      jj_consume_token(RIGHT_PAREN);
    {if (true) return new Char(length);}
      break;
    case DATE:
      jj_consume_token(DATE);
    {if (true) return new Date();}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public TableConstraint tableConstraintDefinition() throws ParseException {
  TableConstraint tableConstratint;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRIMARY:
      tableConstratint = primaryKeyConstraint();
    {if (true) return tableConstratint;}
      break;
    case FOREIGN:
      tableConstratint = referentialConstraint();
    {if (true) return tableConstratint;}
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public schema.tableConstraint.PrimaryKey primaryKeyConstraint() throws ParseException {
  ArrayList<String> columnNameList;
    jj_consume_token(PRIMARY);
    jj_consume_token(KEY);
    columnNameList = columnNameList();
    {if (true) return new schema.tableConstraint.PrimaryKey(columnNameList);}
    throw new Error("Missing return statement in function");
  }

  static final public schema.tableConstraint.ForeignKey referentialConstraint() throws ParseException {
  ArrayList<String> columnNameList;
  String tableName;
  ArrayList<String> referenceColumnNameList;
    jj_consume_token(FOREIGN);
    jj_consume_token(KEY);
    columnNameList = columnNameList();
    jj_consume_token(REFERENCES);
    tableName = tableName();
    referenceColumnNameList = columnNameList();
    {if (true) return new schema.tableConstraint.ForeignKey(columnNameList, tableName, referenceColumnNameList);}
    throw new Error("Missing return statement in function");
  }

  static final public void dropTableQuery() throws ParseException {
  ArrayList<String> tableNameList;
    jj_consume_token(DROP);
    jj_consume_token(TABLE);
    tableNameList = tableNameList();
    jj_consume_token(SEMICOLON);
    try {
      if (tableNameList == null) {
        tables = new HashMap<String, Table>();
        System.out.println("Every table is dropped");
      }
      else {
        for (String tableName : tableNameList) {
          if (!tables.containsKey(tableName)) {
            System.out.println("No such table");
          } else if (tables.get(tableName).isReferenced(new ArrayList<Table>(tables.values()))) {
            System.out.println("Drop table has failed: '" + tableName + "' is referenced by other table");
          } else {
            tables.remove(tableName);
            delete(tableName);
            System.out.println("'" + tableName + "' table is dropped");
          }
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  static final public void showQuery() throws ParseException {
    jj_consume_token(SHOW);
    jj_consume_token(TABLES);
    jj_consume_token(SEMICOLON);
    for (String tableName : tables.keySet()) {
      System.out.println(tableName);
    }
  }

  static final public void descQuery() throws ParseException {
  ArrayList<String> tableNameList;
    jj_consume_token(DESC);
    tableNameList = tableNameList();
    jj_consume_token(SEMICOLON);
    try {
      if (tableNameList == null) {
        if (tables.values().size() == 0) {
          {if (true) return;}
        }
        System.out.println("-------------------------------------------------");
        for (Table table : tables.values())
        {
          table.describeTable();
          System.out.println("-------------------------------------------------");
        }
      } else {
        for (String tableName : tableNameList) {
          if (!tables.containsKey(tableName)) {
            System.out.println("No such table");
            {if (true) return;}
          }
        }
        System.out.println("-------------------------------------------------");
        for (String tableName : tableNameList) {
          tables.get(tableName).describeTable();
          System.out.println("-------------------------------------------------");
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  static final public ArrayList<String> tableNameList() throws ParseException {
  ArrayList<String> tableNameList = new ArrayList<String>();
  String tableName;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STAR:
      jj_consume_token(STAR);
    {if (true) return null;}
      break;
    case LEGAL_IDENTIFIER:
      tableName = tableName();
    tableNameList.add(tableName);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        tableName = tableName();
      tableNameList.add(tableName);
      }
    {if (true) return tableNameList;}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public void selectQuery() throws ParseException {
    jj_consume_token(SELECT);
    selectList();
    tableExpression();
    jj_consume_token(SEMICOLON);
  }

  static final public void selectList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STAR:
      jj_consume_token(STAR);
      break;
    case LEGAL_IDENTIFIER:
      selectedColumn();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[10] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        selectedColumn();
      }
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void selectedColumn() throws ParseException {
    if (jj_2_1(5)) {
      tableName();
      jj_consume_token(PERIOD);
    } else {
      ;
    }
    columnName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      columnName();
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
  }

  static final public void tableExpression() throws ParseException {
    fromClause();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHERE:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_5;
      }
      whereClause();
    }
  }

  static final public void fromClause() throws ParseException {
    jj_consume_token(FROM);
    tableReferenceList();
  }

  static final public void tableReferenceList() throws ParseException {
    referedTable();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      jj_consume_token(COMMA);
      referedTable();
    }
  }

  static final public void referedTable() throws ParseException {
    tableName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      tableName();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  static final public void insertQuery() throws ParseException {
  String tableName;
  ArrayList<String> columnNameList;
  ArrayList<ComparableValue> objectList;
  HashMap<String, Object> sources;
    jj_consume_token(INSERT);
    jj_consume_token(INTO);
    tableName = tableName();
    sources = insertColumnsAndSource();
    jj_consume_token(SEMICOLON);
    Table table = tables.get(tableName);
    if (table == null) {
      System.out.println("No such table");
      {if (true) return;}
    }
    columnNameList = (ArrayList<String>)sources.get("columnNameList");
    if (columnNameList == null) {
      columnNameList = table.getAllColumnsName();
    }
    objectList = (ArrayList<ComparableValue>)sources.get("objectList");
    try {
      for (String columnName : columnNameList) {
        if (!table.hasColumn(columnName)) {
          {if (true) throw new InsertColumnExistenceError(columnName);}
        }
      } // ?óÜ?äî Ïª¨Îüº?ù¥ ?ûà?ùå
      if (objectList.size() > columnNameList.size()) {
        {if (true) throw new InsertTooMuchItemError();}
      } // ?û¨Î£? ?ÑòÏπ?
      for (int i = 0; i < columnNameList.size() - objectList.size(); i++) {
        objectList.add(null);
      } // ?àò ÎßûÏùÑ ?ïåÍπåÏ? nullÎ°? Ï±ÑÏö∞Í∏?
      HashMap<String, ComparableValue> items = new HashMap<String, ComparableValue>();
      for (int i = 0; i < columnNameList.size(); i++) {
        // System.out.println(columnNameList.get(i) +" "+ objectList.get(i));
        items.put(columnNameList.get(i), objectList.get(i));
      }
      Relation relation = (Relation)load(tableName);
      relation.insert(items);
      save(tableName, relation);
      System.out.println("The row is inserted");
    } catch (InsertException e) {
      System.out.println(e.getMessage());
    } catch (Exception e){
      e.printStackTrace();
    }
  }

  static final public HashMap<String, Object> insertColumnsAndSource() throws ParseException {
  ArrayList<String> columnNameList = null;
  ArrayList<ComparableValue> objectList;
  HashMap<String, Object> sources = new HashMap<String, Object>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEFT_PAREN:
      columnNameList = columnNameList();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    objectList = valueList();
    sources.put("columnNameList", columnNameList);
    sources.put("objectList", objectList);
    {if (true) return sources;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<String> columnNameList() throws ParseException {
  ArrayList<String> columnNameList = new ArrayList<String>();
    jj_consume_token(LEFT_PAREN);
    columnNameList.add(columnName());
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      columnNameList.add(columnName());
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return columnNameList;}
    throw new Error("Missing return statement in function");
  }

  static final public String columnName() throws ParseException {
  Token token;
  String columnName = "";
    jj_consume_token(LEGAL_IDENTIFIER);
    token = getToken(0);
    columnName = token.image;
    {if (true) return columnName.toLowerCase();}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<ComparableValue> valueList() throws ParseException {
  ArrayList<ComparableValue> objectList = new ArrayList<ComparableValue>();
  ComparableValue object;
    jj_consume_token(VALUES);
    jj_consume_token(LEFT_PAREN);
    object = value();
    objectList.add(object);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_8;
      }
      jj_consume_token(COMMA);
      object = value();
      objectList.add(object);
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return objectList;}
    throw new Error("Missing return statement in function");
  }

  static final public ComparableValue value() throws ParseException {
  ComparableValue object;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
      jj_consume_token(NULL);
    {if (true) return new ComparableValue(null, null);}
      break;
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      object = comparableValue();
    {if (true) return object;}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public ComparableValue comparableValue() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
      jj_consume_token(INT_VALUE);
    {if (true) return new ComparableValue(Integer.parseInt(getToken(0).image), DataType.Type.INT);}
      break;
    case CHAR_STRING:
      jj_consume_token(CHAR_STRING);
    {if (true) return new ComparableValue(getToken(0).image.substring(1, getToken(0).image.length() - 1), DataType.Type.CHAR);}
      break;
    case DATE_VALUE:
      jj_consume_token(DATE_VALUE);
    {if (true) return new ComparableValue(getToken(0).image, DataType.Type.DATE);}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public void deleteQuery() throws ParseException {
  String tableName;
  WhereClause whereClause = null;
    jj_consume_token(DELETE);
    jj_consume_token(FROM);
    tableName = tableName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      whereClause = whereClause();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
    Relation relation = (Relation)load(tableName);
    if (relation == null) {
      System.out.println("No such table");
      {if (true) return;}
    }
    try {
      int[] result = relation.delete(new ArrayList<Table>(parser.SimpleDBMSParser.tables.values()), whereClause);
      // Î≠îÍ? ?†ïÎ≥¥Î?? Î∞õÏïÑ???Ñú Ï∂úÎ†•?ï¥?ïº?ï®
      if (result[0] != 0) {
        System.out.println(result[0] + " row(s) are deleted");
      }
      if (result[1] != 0) {
        System.out.println(result[1] + " row(s) are not deleted due to referential integrity");
      }
    } catch (WhereClauseException e) {
      System.out.println(e.getMessage());
    }
  }

  static final public String tableName() throws ParseException {
  Token token;
  String tableName = "";
    jj_consume_token(LEGAL_IDENTIFIER);
    token = getToken(0);
    tableName = token.image;
        {if (true) return tableName.toLowerCase();}
    throw new Error("Missing return statement in function");
  }

  static final public WhereClause whereClause() throws ParseException {
  BooleanValueExpression booleanValueExpression;
    jj_consume_token(WHERE);
    booleanValueExpression = booleanValueExpression();
    {if (true) return new WhereClause(booleanValueExpression);}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanValueExpression booleanValueExpression() throws ParseException {
  BooleanValueExpression booleanValueExpression = new BooleanValueExpression();
  BooleanValue booleanValue;
    booleanValue = booleanTerm();
    booleanValueExpression.add(booleanValue);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OR:
      jj_consume_token(OR);
      booleanValue = booleanValueExpression();
      booleanValueExpression.add(booleanValue);
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    {if (true) return booleanValueExpression;}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanValue booleanTerm() throws ParseException {
  BooleanTerm booleanTerm = new BooleanTerm();
  BooleanValue booleanValue;
    // boolean term?ù¥ ?ûà?úºÎ©? Î∞õÏïÑ?Ñú and?ï¥?Ñú Î¶¨ÌÑ¥
      booleanValue = booleanFactor();
    booleanTerm.add(booleanValue);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
      jj_consume_token(AND);
      booleanValue = booleanTerm();
      booleanTerm.add(booleanValue);
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    {if (true) return booleanTerm;}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanValue booleanFactor() throws ParseException {
  boolean isNot = false;
  BooleanValue booleanValue;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      isNot = true;
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    booleanValue = booleanTest();
    {if (true) return new BooleanFactor(isNot, booleanValue);}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanValue booleanTest() throws ParseException {
  BooleanValue booleanValue;
  Predicate predicate;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEGAL_IDENTIFIER:
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      // predicate?? parenthesized boolean expression?ùÑ Î¶¨ÌÑ¥?ï¥?ïº ?ï®
        predicate = predicate();
    {if (true) return new BooleanTest(predicate);}
      break;
    case LEFT_PAREN:
      booleanValue = parenthesizedBooleanExpression();
    {if (true) return booleanValue;}
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Predicate predicate() throws ParseException {
  Predicate predicate;
    if (jj_2_2(4)) {
      // ?ù¥ Î∞ëÏùò Í≤ÉÎì§?? <LEGAL_ID>Í∞? Í≥ÑÏÜç ?Çò???Ñú 4Î≤àÏ? ÎØ∏Î¶¨ Î¥êÎëê?ñ¥?ïº ?ï®
        predicate = comparisonPredicate();
    {if (true) return predicate;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEGAL_IDENTIFIER:
      case INT_VALUE:
      case DATE_VALUE:
      case CHAR_STRING:
        predicate = nullPredicate();
    {if (true) return predicate;}
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public ComparisonPredicate comparisonPredicate() throws ParseException {
  CompOperand compOperand1;
  CompOp compOp;
  CompOperand compOperand2;
    // comp operandÍ∞? Í∞ôÏ? ???ûÖ?ù∏Ïß? ?ôï?ù∏?èÑ ?ï¥?ïº?ï† Í≤? Í∞ôÍ≥† ?ùº?ã® comp operator?óê ÎßûÍ≤å Í≥ÑÏÇ∞?ïú boolean?ùÑ Î¶¨ÌÑ¥
      compOperand1 = compOperand();
    compOp = compOp();
    compOperand2 = compOperand();
    {if (true) return new ComparisonPredicate(compOperand1, compOp, compOperand2);}
    throw new Error("Missing return statement in function");
  }

  static final public CompOperand compOperand() throws ParseException {
  CompOperand compOperand;
  String tableName = null;
  String columnName;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      compOperand = comparableValue();
    {if (true) return compOperand;}
      break;
    case LEGAL_IDENTIFIER:
      if (jj_2_3(2)) {
        // table name?ù∏Ïß? column name?ù∏Ïß? 2Î≤àÏ? ÎØ∏Î¶¨ ?ôï?ù∏?ï¥?ïº?ïú?ã§
            tableName = tableName();
        jj_consume_token(PERIOD);
      } else {
        ;
      }
      columnName = columnName();
    {if (true) return new ColumnElement(tableName, columnName);}
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public CompOp compOp() throws ParseException {
  OperatorType opType;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LESS:
      jj_consume_token(LESS);
      opType = OperatorType.LESS;
      break;
    case GREATER:
      jj_consume_token(GREATER);
      opType = OperatorType.GREATER;
      break;
    case EQUAL:
      jj_consume_token(EQUAL);
      opType = OperatorType.EQUAL;
      break;
    case GREATER_OR_EQUAL:
      jj_consume_token(GREATER_OR_EQUAL);
      opType = OperatorType.GREATER_OR_EQUAL;
      break;
    case LESS_OR_EQUAL:
      jj_consume_token(LESS_OR_EQUAL);
      opType = OperatorType.LESS_OR_EQUAL;
      break;
    case NOT_EQUAL:
      jj_consume_token(NOT_EQUAL);
      opType = OperatorType.NOT_EQUAL;
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new CompOp(opType);}
    throw new Error("Missing return statement in function");
  }

  static final public NullPredicate nullPredicate() throws ParseException {
  CompOperand compOperand;
  String tableName = null;
  String columnName;
  boolean isNot = false;
    // table name?ùò column name?ù¥ (not) null ?ù∏Ïß? ?ôï?ù∏?ïú boolean?ùÑ Î¶¨ÌÑ¥
      compOperand = compOperand();
    jj_consume_token(IS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      isNot = true;
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(NULL);
    {if (true) return new NullPredicate(compOperand, isNot);}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanValue parenthesizedBooleanExpression() throws ParseException {
  BooleanValue booleanValue;
    jj_consume_token(LEFT_PAREN);
    booleanValue = booleanValueExpression();
    jj_consume_token(RIGHT_PAREN);
    {if (true) return booleanValue;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_9()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) return true;
    }
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(DATE_VALUE)) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(NOT_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(CHAR_STRING)) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(LESS_OR_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(INT_VALUE)) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(GREATER_OR_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_3R_11()) return true;
    if (jj_3R_12()) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(GREATER)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(LESS)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SimpleDBMSParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x48b4060,0x48b4040,0x48b4040,0x0,0xc00,0x80000000,0x380,0xc00,0x0,0x100000,0x0,0x100000,0x200000,0x8000000,0x0,0x200000,0x0,0x0,0x0,0x0,0x0,0x8000000,0x10000000,0x20000000,0x80000000,0x0,0x0,0x0,0x0,0x80000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x10,0x2000,0x0,0x0,0x0,0x10,0x2000,0x10,0x2000,0x0,0x0,0x10,0x0,0x4,0x10,0x10,0x94001,0x94000,0x0,0x0,0x0,0x0,0x96004,0x96000,0x96000,0x1f80,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[3];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SimpleDBMSParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SimpleDBMSParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SimpleDBMSParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SimpleDBMSParser(SimpleDBMSParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SimpleDBMSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 30; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
