/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int TABLE = 10;
  /** RegularExpression Id. */
  int PRIMARY = 11;
  /** RegularExpression Id. */
  int FOREIGN = 12;
  /** RegularExpression Id. */
  int KEY = 13;
  /** RegularExpression Id. */
  int REFERENCES = 14;
  /** RegularExpression Id. */
  int DROP = 15;
  /** RegularExpression Id. */
  int STAR = 16;
  /** RegularExpression Id. */
  int DESC = 17;
  /** RegularExpression Id. */
  int SHOW = 18;
  /** RegularExpression Id. */
  int TABLES = 19;
  /** RegularExpression Id. */
  int SELECT = 20;
  /** RegularExpression Id. */
  int AS = 21;
  /** RegularExpression Id. */
  int FROM = 22;
  /** RegularExpression Id. */
  int WHERE = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int INSERT = 26;
  /** RegularExpression Id. */
  int INTO = 27;
  /** RegularExpression Id. */
  int VALUES = 28;
  /** RegularExpression Id. */
  int DELETE = 29;
  /** RegularExpression Id. */
  int IS = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int NULL = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int INT_VALUE = 34;
  /** RegularExpression Id. */
  int CHAR_STRING = 35;
  /** RegularExpression Id. */
  int LEFT_PAREN = 36;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 37;
  /** RegularExpression Id. */
  int COMMA = 38;
  /** RegularExpression Id. */
  int PERIOD = 39;
  /** RegularExpression Id. */
  int UNDERSCORE = 40;
  /** RegularExpression Id. */
  int SIGN = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 43;
  /** RegularExpression Id. */
  int ALPHABET = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;
  /** RegularExpression Id. */
  int GREATER = 46;
  /** RegularExpression Id. */
  int LESS = 47;
  /** RegularExpression Id. */
  int EQUAL = 48;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 49;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 50;
  /** RegularExpression Id. */
  int NOT_EQUAL = 51;
  /** RegularExpression Id. */
  int NNNN = 52;
  /** RegularExpression Id. */
  int NN = 53;
  /** RegularExpression Id. */
  int DATE_VALUE = 54;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 55;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"table\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\"drop\"",
    "\"*\"",
    "\"desc\"",
    "\"show\"",
    "\"tables\"",
    "\"select\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"insert\"",
    "\"into\"",
    "\"values\"",
    "\"delete\"",
    "\"is\"",
    "\"not\"",
    "\"null\"",
    "\";\"",
    "<INT_VALUE>",
    "<CHAR_STRING>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<QUOTE>",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "<NNNN>",
    "<NN>",
    "<DATE_VALUE>",
    "<NON_QUOTE_CHARACTER>",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
  };

}
